/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game;

import deckCreate.DBM;
import deckCreate.FirstPg;
import java.awt.Rectangle;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 * <p>
 * Game class.</p>
 *
 * @author rekat
 * @version $Id: $Id
 */
public class Game extends javax.swing.JFrame {

    GameAlgorithms GA = new GameAlgorithms();
    DBM dbm = new DBM();

    /**
     * Creates new form Game
     */
    public Game() {
        initComponents();
        myInitComponents();

    }

    public void myInitComponents() {
        Username.setText(GA.getPlayername());
        btnNewButton_5_1.setVisible(false);
        btnNewButton_5.setVisible(false);
        btnEnd.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNewLabel_1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        lblNewLabel_2 = new javax.swing.JLabel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelB = new javax.swing.JLabel();
        jLabelD = new javax.swing.JLabel();
        jLabelA = new javax.swing.JLabel();
        jLabelC = new javax.swing.JLabel();
        btnEnd = new javax.swing.JButton();
        btnNewButton = new javax.swing.JButton();
        btnNewButton_6_2 = new javax.swing.JButton();
        btnNewButton_2 = new javax.swing.JButton();
        btnNewButton_1 = new javax.swing.JButton();
        btnNewButton_3 = new javax.swing.JButton();
        btnNewButton_5 = new javax.swing.JButton();
        btnNewButton_4 = new javax.swing.JButton();
        btnNewButton_6 = new javax.swing.JButton();
        btnNewButton_6_1 = new javax.swing.JButton();
        btnNewButton_5_1 = new javax.swing.JButton();
        textField = new javax.swing.JTextField();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Legyen Ön is milliomos!");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.setLayout(null);

        lblNewLabel_1.setBackground(new java.awt.Color(255, 255, 255));
        lblNewLabel_1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblNewLabel_1.setForeground(new java.awt.Color(255, 255, 255));
        lblNewLabel_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNewLabel_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lblNewLabel_1);
        lblNewLabel_1.setBounds(70, 50, 690, 140);

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SEGÍTSÉGEK");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(910, 390, 120, 50);

        Username.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        Username.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(Username);
        Username.setBounds(93, 10, 270, 20);

        lblNewLabel_2.setForeground(new java.awt.Color(255, 255, 255));
        lblNewLabel_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNewLabel_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblNewLabel_2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblNewLabel_2);
        lblNewLabel_2.setBounds(70, 200, 690, 60);

        kGradientPanel2.setkEndColor(new java.awt.Color(21, 2, 77));
        kGradientPanel2.setkGradientFocus(400);
        kGradientPanel2.setkStartColor(new java.awt.Color(49, 13, 252));
        kGradientPanel2.setMaximumSize(new java.awt.Dimension(345, 140));
        kGradientPanel2.setName(""); // NOI18N

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel1.add(kGradientPanel2);
        kGradientPanel2.setBounds(70, 200, 690, 60);

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Sok sikert");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 10, 80, 20);

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Jelenlegi összeg");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(770, 10, 130, 30);

        jLabelB.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabelB.setForeground(new java.awt.Color(255, 255, 255));
        jLabelB.setText("B");
        jPanel1.add(jLabelB);
        jLabelB.setBounds(460, 335, 20, 30);

        jLabelD.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabelD.setForeground(new java.awt.Color(255, 255, 255));
        jLabelD.setText("D");
        jPanel1.add(jLabelD);
        jLabelD.setBounds(460, 445, 20, 30);

        jLabelA.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabelA.setForeground(new java.awt.Color(255, 255, 255));
        jLabelA.setText("A");
        jPanel1.add(jLabelA);
        jLabelA.setBounds(80, 335, 20, 30);

        jLabelC.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabelC.setForeground(new java.awt.Color(255, 255, 255));
        jLabelC.setText("C");
        jPanel1.add(jLabelC);
        jLabelC.setBounds(80, 445, 20, 30);

        btnEnd.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        btnEnd.setForeground(new java.awt.Color(0, 0, 102));
        btnEnd.setText("Játék vége");
        btnEnd.setBorder(null);
        btnEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEndActionPerformed(evt);
            }
        });
        jPanel1.add(btnEnd);
        btnEnd.setBounds(320, 550, 200, 40);

        btnNewButton.setBackground(new java.awt.Color(34, 7, 159));
        btnNewButton.setForeground(new java.awt.Color(255, 255, 255));
        btnNewButton.setBorder(null);
        btnNewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewButtonActionPerformed(evt);
            }
        });
        jPanel1.add(btnNewButton);
        btnNewButton.setBounds(70, 310, 310, 80);

        btnNewButton_6_2.setBackground(new java.awt.Color(34, 7, 159));
        btnNewButton_6_2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnNewButton_6_2.setForeground(new java.awt.Color(255, 255, 255));
        btnNewButton_6_2.setText("Telefon");
        btnNewButton_6_2.setBorder(null);
        btnNewButton_6_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewButton_6_2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnNewButton_6_2);
        btnNewButton_6_2.setBounds(910, 520, 120, 30);

        btnNewButton_2.setBackground(new java.awt.Color(34, 7, 159));
        btnNewButton_2.setForeground(new java.awt.Color(255, 255, 255));
        btnNewButton_2.setBorder(null);
        btnNewButton_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewButton_2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnNewButton_2);
        btnNewButton_2.setBounds(70, 420, 310, 80);

        btnNewButton_1.setBackground(new java.awt.Color(34, 7, 159));
        btnNewButton_1.setForeground(new java.awt.Color(255, 255, 255));
        btnNewButton_1.setBorder(null);
        btnNewButton_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewButton_1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnNewButton_1);
        btnNewButton_1.setBounds(450, 310, 310, 80);

        btnNewButton_3.setBackground(new java.awt.Color(34, 7, 159));
        btnNewButton_3.setForeground(new java.awt.Color(255, 255, 255));
        btnNewButton_3.setBorder(null);
        btnNewButton_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewButton_3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnNewButton_3);
        btnNewButton_3.setBounds(450, 420, 310, 80);

        btnNewButton_5.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        btnNewButton_5.setForeground(new java.awt.Color(0, 0, 102));
        btnNewButton_5.setText("Tovább");
        btnNewButton_5.setBorder(null);
        btnNewButton_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewButton_5ActionPerformed(evt);
            }
        });
        jPanel1.add(btnNewButton_5);
        btnNewButton_5.setBounds(320, 530, 200, 40);

        btnNewButton_4.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        btnNewButton_4.setForeground(new java.awt.Color(0, 0, 102));
        btnNewButton_4.setText("Start");
        btnNewButton_4.setBorder(null);
        btnNewButton_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewButton_4ActionPerformed(evt);
            }
        });
        jPanel1.add(btnNewButton_4);
        btnNewButton_4.setBounds(870, 570, 200, 50);

        btnNewButton_6.setBackground(new java.awt.Color(34, 7, 159));
        btnNewButton_6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnNewButton_6.setForeground(new java.awt.Color(255, 255, 255));
        btnNewButton_6.setText("Felező");
        btnNewButton_6.setBorder(null);
        btnNewButton_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewButton_6ActionPerformed(evt);
            }
        });
        jPanel1.add(btnNewButton_6);
        btnNewButton_6.setBounds(910, 440, 120, 30);

        btnNewButton_6_1.setBackground(new java.awt.Color(34, 7, 159));
        btnNewButton_6_1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnNewButton_6_1.setForeground(new java.awt.Color(255, 255, 255));
        btnNewButton_6_1.setText("Közönség");
        btnNewButton_6_1.setBorder(null);
        btnNewButton_6_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewButton_6_1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnNewButton_6_1);
        btnNewButton_6_1.setBounds(910, 480, 120, 30);

        btnNewButton_5_1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        btnNewButton_5_1.setForeground(new java.awt.Color(0, 0, 102));
        btnNewButton_5_1.setText("Megáll");
        btnNewButton_5_1.setBorder(null);
        btnNewButton_5_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewButton_5_1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnNewButton_5_1);
        btnNewButton_5_1.setBounds(320, 580, 200, 40);

        textField.setEditable(false);
        textField.setBackground(new java.awt.Color(21, 2, 77));
        textField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        textField.setForeground(new java.awt.Color(255, 255, 255));
        textField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField.setToolTipText("");
        textField.setBorder(null);
        textField.setHighlighter(null);
        textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldActionPerformed(evt);
            }
        });
        jPanel1.add(textField);
        textField.setBounds(900, 10, 160, 30);

        kGradientPanel1.setkEndColor(new java.awt.Color(21, 2, 77));
        kGradientPanel1.setkGradientFocus(400);
        kGradientPanel1.setkStartColor(new java.awt.Color(49, 13, 252));
        kGradientPanel1.setMaximumSize(new java.awt.Dimension(345, 140));
        kGradientPanel1.setName(""); // NOI18N

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        jPanel1.add(kGradientPanel1);
        kGradientPanel1.setBounds(70, 50, 690, 140);

        list.setBackground(new java.awt.Color(21, 2, 77));
        list.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        list.setForeground(new java.awt.Color(255, 255, 255));
        list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Kezdés", "1.   10 000 Ft ", "2.   20 000 Ft", "3.   50 000 Ft", "4.   100 000 Ft", "5.   250 000 Ft (szakaszkérdés)", "6.   500 000 Ft", "7.   750 000 Ft", "8.   1 000 000 Ft", "9.   1 500 000 Ft", "10.   2 000 000 Ft (szakaszkérdés)", "11.   5 000 000 Ft", "12.   10 000 000 Ft", "13.   15 000 000 Ft", "14.   25 000 000 Ft", "15.   50 000 000 Ft", "Item 15" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        list.setMaximumSize(new java.awt.Dimension(50, 270));
        list.setMinimumSize(new java.awt.Dimension(50, 270));
        list.setPreferredSize(new java.awt.Dimension(50, 270));
        list.setSelectionBackground(new java.awt.Color(49, 13, 252));
        list.setVisibleRowCount(9);
        jScrollPane1.setViewportView(list);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(850, 50, 230, 340);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\TeglasRekaSzakdolgozat\\img\\bg.png")); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-80, 0, 1540, 660);

        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuBar1.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N

        jMenu1.setText("Menü");
        jMenu1.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon("C:\\TeglasRekaSzakdolgozat\\img\\icons8-back-arrow-20.png")); // NOI18N
        jMenuItem1.setText("Vissza");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        menuExit.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        menuExit.setIcon(new javax.swing.ImageIcon("C:\\TeglasRekaSzakdolgozat\\img\\icons8-exit-20.png")); // NOI18N
        menuExit.setText("Kilépés");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        jMenu1.add(menuExit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1458, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewButton_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewButton_5ActionPerformed

        GA.pausegame(btnNewButton_5, btnNewButton_5_1, evt, btnEnd);
        GA.TestMaker(btnNewButton, btnNewButton_1, btnNewButton_2, btnNewButton_3, lblNewLabel_1, evt,
                lblNewLabel_2);
        list.setSelectedIndex(GA.getI());

    }//GEN-LAST:event_btnNewButton_5ActionPerformed

    private void textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldActionPerformed

    private void btnNewButton_6_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewButton_6_2ActionPerformed
        GA.playerhelp3(btnNewButton, btnNewButton_1, btnNewButton_2, btnNewButton_3, btnNewButton_6_2);
    }//GEN-LAST:event_btnNewButton_6_2ActionPerformed

    private void btnNewButton_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewButton_6ActionPerformed
        GA.playerhelp1(btnNewButton, btnNewButton_1, btnNewButton_2, btnNewButton_3, btnNewButton_6, jLabelA, jLabelB, jLabelC, jLabelD);
    }//GEN-LAST:event_btnNewButton_6ActionPerformed

    private void btnNewButton_6_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewButton_6_1ActionPerformed
        try {
            GA.playerhelp2randomizer(btnNewButton, btnNewButton_1, btnNewButton_2, btnNewButton_3, btnNewButton_6_1);
        } catch (IOException ex) {
            Logger.getLogger(Game.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnNewButton_6_1ActionPerformed

    private void btnNewButton_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewButton_4ActionPerformed

        GA.GetQuestion();
        GA.TestMaker(btnNewButton, btnNewButton_1, btnNewButton_2, btnNewButton_3, lblNewLabel_1, evt,
                lblNewLabel_2);
        list.setSelectedIndex(GA.getI());
        GA.endgame();
        btnNewButton_4.setVisible(false);

    }//GEN-LAST:event_btnNewButton_4ActionPerformed

    private void btnNewButton_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewButton_2ActionPerformed
        GA.endgame();
        GA.saveq(btnNewButton, btnNewButton_1, btnNewButton_2, btnNewButton_3, evt, textField, jLabelA, jLabelB, jLabelC, jLabelD);

        if (GA.pausegame(btnNewButton_5_1, btnNewButton_5, evt, btnEnd) == true) {
            GA.TestMaker(btnNewButton, btnNewButton_1, btnNewButton_2, btnNewButton_3, lblNewLabel_1, evt,
                    lblNewLabel_2);
            list.setSelectedIndex(GA.getI());
        }

    }//GEN-LAST:event_btnNewButton_2ActionPerformed

    private void btnNewButton_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewButton_1ActionPerformed
        GA.endgame();
        GA.saveq(btnNewButton, btnNewButton_1, btnNewButton_2, btnNewButton_3, evt, textField, jLabelA, jLabelB, jLabelC, jLabelD);

        if (GA.pausegame(btnNewButton_5_1, btnNewButton_5, evt, btnEnd) == true) {
            GA.TestMaker(btnNewButton, btnNewButton_1, btnNewButton_2, btnNewButton_3, lblNewLabel_1, evt,
                    lblNewLabel_2);
            list.setSelectedIndex(GA.getI());
        }

    }//GEN-LAST:event_btnNewButton_1ActionPerformed

    private void btnNewButton_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewButton_3ActionPerformed
        GA.endgame();
        GA.saveq(btnNewButton, btnNewButton_1, btnNewButton_2, btnNewButton_3, evt, textField, jLabelA, jLabelB, jLabelC, jLabelD);
        if (GA.pausegame(btnNewButton_5_1, btnNewButton_5, evt, btnEnd) == true) {
            GA.TestMaker(btnNewButton, btnNewButton_1, btnNewButton_2, btnNewButton_3, lblNewLabel_1, evt,
                    lblNewLabel_2);
            list.setSelectedIndex(GA.getI());
        }

    }//GEN-LAST:event_btnNewButton_3ActionPerformed

    private void btnNewButton_5_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewButton_5_1ActionPerformed

        GA.pausegame(btnNewButton_5, btnNewButton_5_1, evt, btnEnd);
        dispose();
        setVisible(false);
        FirstPg FP = new FirstPg();
        FP.setVisible(true);

    }//GEN-LAST:event_btnNewButton_5_1ActionPerformed

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuExitActionPerformed

    private void btnNewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewButtonActionPerformed
        GA.endgame();
        GA.saveq(btnNewButton, btnNewButton_1, btnNewButton_2, btnNewButton_3, evt, textField, jLabelA, jLabelB, jLabelC, jLabelD);

        if (GA.pausegame(btnNewButton_5_1, btnNewButton_5, evt, btnEnd) == true) {
            GA.TestMaker(btnNewButton, btnNewButton_1, btnNewButton_2, btnNewButton_3, lblNewLabel_1, evt,
                    lblNewLabel_2);
            list.setSelectedIndex(GA.getI());
        }

    }//GEN-LAST:event_btnNewButtonActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        PreGame pregame = new PreGame();
        setVisible(false);
        dispose();
        pregame.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEndActionPerformed
        GA.endgame();
        dispose();
        setVisible(false);
        FirstPg FP = new FirstPg();
        FP.setVisible(true);
    }//GEN-LAST:event_btnEndActionPerformed

    /**
     * <p>
     * main.</p>
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Username;
    private javax.swing.JButton btnEnd;
    private javax.swing.JButton btnNewButton;
    private javax.swing.JButton btnNewButton_1;
    private javax.swing.JButton btnNewButton_2;
    private javax.swing.JButton btnNewButton_3;
    private javax.swing.JButton btnNewButton_4;
    private javax.swing.JButton btnNewButton_5;
    private javax.swing.JButton btnNewButton_5_1;
    private javax.swing.JButton btnNewButton_6;
    private javax.swing.JButton btnNewButton_6_1;
    private javax.swing.JButton btnNewButton_6_2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelA;
    private javax.swing.JLabel jLabelB;
    private javax.swing.JLabel jLabelC;
    private javax.swing.JLabel jLabelD;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JLabel lblNewLabel_1;
    private javax.swing.JLabel lblNewLabel_2;
    private javax.swing.JList<String> list;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JTextField textField;
    // End of variables declaration//GEN-END:variables
}
