/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game;

/**
 * <p>
 * Ranking class.</p>
 *
 * @author rekat
 * @version $Id: $Id
 */
public class Ranking extends javax.swing.JFrame {

    /**
     * Creates new form Ranking
     */
    public Ranking() {
        GameAlgorithms GA = new GameAlgorithms();
        initComponents();
        GA.ranking(textArea, textArea1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        scrollPane1 = new javax.swing.JScrollPane();
        textArea1 = new javax.swing.JTextArea();
        scrollPane = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Legyen Ön is milliomos! toplista");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contentPane.setBackground(new java.awt.Color(0, 0, 102));
        contentPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        contentPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Top10 lista");
        contentPane.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 350, 70));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Legnagyobb megnyert összeg");
        contentPane.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 360, 40));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Felhasználónév");
        contentPane.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 280, 40));

        scrollPane1.setFocusable(false);
        scrollPane1.setPreferredSize(new java.awt.Dimension(400, 400));

        textArea1.setEditable(false);
        textArea1.setBackground(new java.awt.Color(204, 204, 204));
        textArea1.setColumns(20);
        textArea1.setFont(new java.awt.Font("Monospaced", 1, 22)); // NOI18N
        textArea1.setForeground(new java.awt.Color(255, 255, 255));
        textArea1.setRows(5);
        textArea1.setToolTipText("");
        textArea1.setFocusable(false);
        textArea1.setMargin(new java.awt.Insets(2, 0, 2, 2));
        scrollPane1.setViewportView(textArea1);

        contentPane.add(scrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 350, 390));

        scrollPane.setFocusable(false);

        textArea.setEditable(false);
        textArea.setBackground(new java.awt.Color(204, 204, 204));
        textArea.setColumns(20);
        textArea.setFont(new java.awt.Font("Monospaced", 1, 22)); // NOI18N
        textArea.setForeground(new java.awt.Color(255, 255, 255));
        textArea.setRows(5);
        textArea.setToolTipText("");
        textArea.setFocusable(false);
        textArea.setMargin(new java.awt.Insets(2, 2, 2, 0));
        scrollPane.setViewportView(textArea);

        contentPane.add(scrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 420, 390));

        getContentPane().add(contentPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 620));

        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuBar1.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N

        jMenu1.setText("Menü");
        jMenu1.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon("C:\\TeglasRekaSzakdolgozat\\img\\icons8-back-arrow-20.png")); // NOI18N
        jMenuItem1.setText("Vissza");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        menuExit.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        menuExit.setIcon(new javax.swing.ImageIcon("C:\\TeglasRekaSzakdolgozat\\img\\icons8-exit-20.png")); // NOI18N
        menuExit.setText("Kilépés");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        jMenu1.add(menuExit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        PreGame pregame = new PreGame();
        setVisible(false);
        dispose();
        pregame.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuExitActionPerformed

    /**
     * <p>
     * main.</p>
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ranking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JScrollPane scrollPane1;
    private javax.swing.JTextArea textArea;
    private javax.swing.JTextArea textArea1;
    // End of variables declaration//GEN-END:variables
}
