/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package deckCreate;

import game.GameAlgorithms;
import java.awt.Color;

/**
 * <p>
 * DeckCreate class.</p>
 *
 * @author rekat
 * @version $Id: $Id
 */
public class DeckCreate extends javax.swing.JFrame {

    DBM dbm = new DBM();
    String colour = "";
    GameAlgorithms GA = new GameAlgorithms();

    /**
     * Creates new form DeckCreate
     */
    public DeckCreate() {
        initComponents();
        myInitComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void myInitComponents() {
        GameAlgorithms GA = new GameAlgorithms();
        username.setText(GA.getPlayername());
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPane = new javax.swing.JPanel();
        panel = new javax.swing.JPanel();
        panel_7_1 = new javax.swing.JPanel();
        panel_1 = new javax.swing.JPanel();
        panel_7_2 = new javax.swing.JPanel();
        panel_2 = new javax.swing.JPanel();
        panel_7_3 = new javax.swing.JPanel();
        panel_3 = new javax.swing.JPanel();
        panel_7_4 = new javax.swing.JPanel();
        panel_4 = new javax.swing.JPanel();
        panel_7_5 = new javax.swing.JPanel();
        panel_5 = new javax.swing.JPanel();
        panel_7_6 = new javax.swing.JPanel();
        cb1 = new javax.swing.JCheckBox();
        cb2 = new javax.swing.JCheckBox();
        cb3 = new javax.swing.JCheckBox();
        cb4 = new javax.swing.JCheckBox();
        cb5 = new javax.swing.JCheckBox();
        cb6 = new javax.swing.JCheckBox();
        lblNewLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panel_6 = new javax.swing.JPanel();
        panel_7_7 = new javax.swing.JPanel();
        textField_14 = new javax.swing.JTextField();
        btnNewButton = new javax.swing.JButton();
        btnNewButton_1 = new javax.swing.JButton();
        username = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kártyapakli készítő");

        contentPane.setBackground(new java.awt.Color(238, 254, 254));
        contentPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        contentPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel.setBackground(new java.awt.Color(204, 255, 255));
        panel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_7_1.setBackground(new java.awt.Color(255, 255, 255));
        panel_7_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout panel_7_1Layout = new javax.swing.GroupLayout(panel_7_1);
        panel_7_1.setLayout(panel_7_1Layout);
        panel_7_1Layout.setHorizontalGroup(
            panel_7_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 146, Short.MAX_VALUE)
        );
        panel_7_1Layout.setVerticalGroup(
            panel_7_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        panel.add(panel_7_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 12, -1, -1));

        contentPane.add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 170, 230));

        panel_1.setBackground(new java.awt.Color(204, 255, 204));
        panel_1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        panel_1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_7_2.setBackground(new java.awt.Color(255, 255, 255));
        panel_7_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout panel_7_2Layout = new javax.swing.GroupLayout(panel_7_2);
        panel_7_2.setLayout(panel_7_2Layout);
        panel_7_2Layout.setHorizontalGroup(
            panel_7_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 146, Short.MAX_VALUE)
        );
        panel_7_2Layout.setVerticalGroup(
            panel_7_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        panel_1.add(panel_7_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 12, -1, -1));

        contentPane.add(panel_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 170, 230));

        panel_2.setBackground(new java.awt.Color(255, 255, 204));
        panel_2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        panel_2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_7_3.setBackground(new java.awt.Color(255, 255, 255));
        panel_7_3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout panel_7_3Layout = new javax.swing.GroupLayout(panel_7_3);
        panel_7_3.setLayout(panel_7_3Layout);
        panel_7_3Layout.setHorizontalGroup(
            panel_7_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 146, Short.MAX_VALUE)
        );
        panel_7_3Layout.setVerticalGroup(
            panel_7_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        panel_2.add(panel_7_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 12, -1, -1));

        contentPane.add(panel_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, 170, 230));

        panel_3.setBackground(new java.awt.Color(255, 170, 150));
        panel_3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        panel_3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_7_4.setBackground(new java.awt.Color(255, 255, 255));
        panel_7_4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout panel_7_4Layout = new javax.swing.GroupLayout(panel_7_4);
        panel_7_4.setLayout(panel_7_4Layout);
        panel_7_4Layout.setHorizontalGroup(
            panel_7_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 146, Short.MAX_VALUE)
        );
        panel_7_4Layout.setVerticalGroup(
            panel_7_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        panel_3.add(panel_7_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 12, -1, -1));

        contentPane.add(panel_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 170, 230));

        panel_4.setBackground(new java.awt.Color(204, 204, 255));
        panel_4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        panel_4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_7_5.setBackground(new java.awt.Color(255, 255, 255));
        panel_7_5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout panel_7_5Layout = new javax.swing.GroupLayout(panel_7_5);
        panel_7_5.setLayout(panel_7_5Layout);
        panel_7_5Layout.setHorizontalGroup(
            panel_7_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 146, Short.MAX_VALUE)
        );
        panel_7_5Layout.setVerticalGroup(
            panel_7_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        panel_4.add(panel_7_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 12, -1, -1));

        contentPane.add(panel_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 170, 230));

        panel_5.setBackground(new java.awt.Color(255, 204, 204));
        panel_5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        panel_5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_7_6.setBackground(new java.awt.Color(255, 255, 255));
        panel_7_6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout panel_7_6Layout = new javax.swing.GroupLayout(panel_7_6);
        panel_7_6.setLayout(panel_7_6Layout);
        panel_7_6Layout.setHorizontalGroup(
            panel_7_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 146, Short.MAX_VALUE)
        );
        panel_7_6Layout.setVerticalGroup(
            panel_7_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        panel_5.add(panel_7_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 12, -1, -1));

        contentPane.add(panel_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 380, 170, 230));

        cb1.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        cb1.setText("Választ");
        cb1.setOpaque(false);
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });
        contentPane.add(cb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 100, -1));

        cb2.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        cb2.setText("Választ");
        cb2.setOpaque(false);
        cb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb2ActionPerformed(evt);
            }
        });
        contentPane.add(cb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 100, -1));

        cb3.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        cb3.setText("Választ");
        cb3.setOpaque(false);
        cb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb3ActionPerformed(evt);
            }
        });
        contentPane.add(cb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 90, 100, -1));

        cb4.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        cb4.setText("Választ");
        cb4.setOpaque(false);
        cb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb4ActionPerformed(evt);
            }
        });
        contentPane.add(cb4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 100, -1));

        cb5.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        cb5.setText("Választ");
        cb5.setOpaque(false);
        cb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb5ActionPerformed(evt);
            }
        });
        contentPane.add(cb5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 100, -1));

        cb6.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        cb6.setText("Választ");
        cb6.setOpaque(false);
        cb6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb6ActionPerformed(evt);
            }
        });
        contentPane.add(cb6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 360, 100, -1));

        lblNewLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 32)); // NOI18N
        lblNewLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNewLabel.setText("Válassz színt a kártyádnak!");
        contentPane.add(lblNewLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 500, 60));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jLabel2.setText("Add meg hexa kódban a színt!");
        contentPane.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 90, 170, 20));

        panel_6.setBackground(new java.awt.Color(255, 255, 255));
        panel_6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        panel_6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_7_7.setBackground(new java.awt.Color(255, 255, 255));
        panel_7_7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout panel_7_7Layout = new javax.swing.GroupLayout(panel_7_7);
        panel_7_7.setLayout(panel_7_7Layout);
        panel_7_7Layout.setHorizontalGroup(
            panel_7_7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 146, Short.MAX_VALUE)
        );
        panel_7_7Layout.setVerticalGroup(
            panel_7_7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        panel_6.add(panel_7_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 12, -1, -1));

        contentPane.add(panel_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 110, 170, 230));

        textField_14.setText("#");
        textField_14.setToolTipText("A hexa-kódot '#'-el add meg!");
        textField_14.setSelectionColor(new java.awt.Color(153, 204, 255));
        textField_14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_14ActionPerformed(evt);
            }
        });
        contentPane.add(textField_14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 370, 170, -1));

        btnNewButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        btnNewButton.setText("Mutat");
        btnNewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewButtonActionPerformed(evt);
            }
        });
        contentPane.add(btnNewButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 400, 90, -1));

        btnNewButton_1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        btnNewButton_1.setText("Tovább");
        btnNewButton_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewButton_1ActionPerformed(evt);
            }
        });
        contentPane.add(btnNewButton_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 580, 170, 35));

        username.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        username.setForeground(new java.awt.Color(0, 63, 117));
        username.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        contentPane.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 290, 20));

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\TeglasRekaSzakdolgozat\\img\\icons8-back-20.png")); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        contentPane.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1380, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPane, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb6ActionPerformed

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb1ActionPerformed

    private void cb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb4ActionPerformed

    private void cb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb5ActionPerformed

    private void cb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb2ActionPerformed

    private void cb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb3ActionPerformed

    private void textField_14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_14ActionPerformed

    private void btnNewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewButtonActionPerformed
        colour = textField_14.getText();
        panel_6.setBackground(Color.decode(colour));
        panel_6.revalidate();
        panel_6.repaint();

    }//GEN-LAST:event_btnNewButtonActionPerformed

    private void btnNewButton_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewButton_1ActionPerformed

        if (cb1.isSelected()) {
            lblNewLabel.setText("BLUE");
            colour = "#CCFFFF";
        } else if (cb2.isSelected()) {
            lblNewLabel.setText("GREEN");
            colour = "#CCFFCC";
        } else if (cb3.isSelected()) {
            lblNewLabel.setText("YELLOW");
            colour = "#FFFFCC";
        } else if (cb4.isSelected()) {
            lblNewLabel.setText("ORANGE");
            colour = "#FFAA96";
        } else if (cb5.isSelected()) {
            lblNewLabel.setText("PURPLE");
            colour = "#CCCCFF";
        } else if (cb6.isSelected()) {
            lblNewLabel.setText("PINK");
            colour = "#FFCCCC";
        } else {
            lblNewLabel.setText(textField_14.getText());
            colour = textField_14.getText();
        }

        dbm.setColour(colour);

        dispose();
        setVisible(false);
        TextEditor te = new TextEditor();
        te.setVisible(true);

    }//GEN-LAST:event_btnNewButton_1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        setVisible(false);
        FirstPg FP = new FirstPg();
        FP.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * <p>
     * main.</p>
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeckCreate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeckCreate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeckCreate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeckCreate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeckCreate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNewButton;
    private javax.swing.JButton btnNewButton_1;
    private javax.swing.JCheckBox cb1;
    private javax.swing.JCheckBox cb2;
    private javax.swing.JCheckBox cb3;
    private javax.swing.JCheckBox cb4;
    private javax.swing.JCheckBox cb5;
    private javax.swing.JCheckBox cb6;
    private javax.swing.JPanel contentPane;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblNewLabel;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel panel_1;
    private javax.swing.JPanel panel_2;
    private javax.swing.JPanel panel_3;
    private javax.swing.JPanel panel_4;
    private javax.swing.JPanel panel_5;
    private javax.swing.JPanel panel_6;
    private javax.swing.JPanel panel_7_1;
    private javax.swing.JPanel panel_7_2;
    private javax.swing.JPanel panel_7_3;
    private javax.swing.JPanel panel_7_4;
    private javax.swing.JPanel panel_7_5;
    private javax.swing.JPanel panel_7_6;
    private javax.swing.JPanel panel_7_7;
    private javax.swing.JTextField textField_14;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
