/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package deckCreate;

import game.Game;
import game.PreGame;

/**
 * <p>
 * FirstPg class.</p>
 *
 * @author rekat
 * @version $Id: $Id
 */
public class FirstPg extends javax.swing.JFrame {

    DBM dbm = new DBM();

    /**
     * Creates new form FirstPg
     */
    public FirstPg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPane = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnNewButton = new javax.swing.JButton();
        btnGame = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        mnNewMenu = new javax.swing.JMenu();
        mntmNewMenuItem_3 = new javax.swing.JMenuItem();
        mntmNewMenuItem_2 = new javax.swing.JMenuItem();
        mntmNewMenuItem_1 = new javax.swing.JMenuItem();
        menuExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kvíz világ");

        contentPane.setBackground(new java.awt.Color(204, 204, 204));
        contentPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\TeglasRekaSzakdolgozat\\img\\icons8-game-controller-40.png")); // NOI18N
        contentPane.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 325, 40, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\TeglasRekaSzakdolgozat\\img\\icons8-cards-40.png")); // NOI18N
        contentPane.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(755, 325, 40, 50));

        btnNewButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        btnNewButton.setForeground(new java.awt.Color(0, 0, 102));
        btnNewButton.setText("Kártyapakli készítés");
        btnNewButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnNewButton.setBorderPainted(false);
        btnNewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewButtonActionPerformed(evt);
            }
        });
        contentPane.add(btnNewButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 300, 100));

        btnGame.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        btnGame.setForeground(new java.awt.Color(0, 0, 102));
        btnGame.setText("Játék indítása");
        btnGame.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnGame.setBorderPainted(false);
        btnGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGameActionPerformed(evt);
            }
        });
        contentPane.add(btnGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 300, 100));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Kérlek válassz!");
        contentPane.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 107, 180, 30));

        jPanel3.setBackground(new java.awt.Color(0, 0, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\TeglasRekaSzakdolgozat\\img\\icons8-questions-64.png")); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 32, -1, -1));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Üdvözöllek a kvíz világában!");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 32, 500, 64));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\TeglasRekaSzakdolgozat\\img\\icons8-questions-64.png")); // NOI18N
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 32, -1, -1));

        contentPane.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 190));

        menuBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        menuBar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuBar.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N

        mnNewMenu.setText("Menü");
        mnNewMenu.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N

        mntmNewMenuItem_3.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 11)); // NOI18N
        mntmNewMenuItem_3.setIcon(new javax.swing.ImageIcon("C:\\TeglasRekaSzakdolgozat\\img\\icons8-print-20.png")); // NOI18N
        mntmNewMenuItem_3.setText("Pakli nyomtatása");
        mntmNewMenuItem_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntmNewMenuItem_3ActionPerformed(evt);
            }
        });
        mnNewMenu.add(mntmNewMenuItem_3);

        mntmNewMenuItem_2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 11)); // NOI18N
        mntmNewMenuItem_2.setIcon(new javax.swing.ImageIcon("C:\\TeglasRekaSzakdolgozat\\img\\icons8-copy-20.png")); // NOI18N
        mntmNewMenuItem_2.setText("Pakli másolása");
        mntmNewMenuItem_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntmNewMenuItem_2ActionPerformed(evt);
            }
        });
        mnNewMenu.add(mntmNewMenuItem_2);

        mntmNewMenuItem_1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 11)); // NOI18N
        mntmNewMenuItem_1.setIcon(new javax.swing.ImageIcon("C:\\TeglasRekaSzakdolgozat\\img\\icons8-update-20.png")); // NOI18N
        mntmNewMenuItem_1.setText("Pakli frissítése");
        mntmNewMenuItem_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntmNewMenuItem_1ActionPerformed(evt);
            }
        });
        mnNewMenu.add(mntmNewMenuItem_1);

        menuExit.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 11)); // NOI18N
        menuExit.setIcon(new javax.swing.ImageIcon("C:\\TeglasRekaSzakdolgozat\\img\\icons8-exit-20.png")); // NOI18N
        menuExit.setText("Kilépés");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        mnNewMenu.add(menuExit);

        menuBar.add(mnNewMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPane, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewButtonActionPerformed
        dispose();
        DeckCreate dc = new DeckCreate();
        dc.setVisible(true);
    }//GEN-LAST:event_btnNewButtonActionPerformed

    private void btnGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGameActionPerformed
        PreGame pregame = new PreGame();
        setVisible(false);
        dispose();
        pregame.setVisible(true);
    }//GEN-LAST:event_btnGameActionPerformed

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuExitActionPerformed

    private void mntmNewMenuItem_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntmNewMenuItem_3ActionPerformed
        dispose();
        setVisible(false);
        Selector se = new Selector();
        dbm.setBtn3(true);
        dbm.setBtn4(false);
        dbm.setTextf(false);
        dbm.setTlabel(false);
        se.setVisible(true);
    }//GEN-LAST:event_mntmNewMenuItem_3ActionPerformed

    private void mntmNewMenuItem_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntmNewMenuItem_2ActionPerformed
        dispose();
        setVisible(false);
        Selector se = new Selector();
        dbm.setBtn1(true);
        dbm.setBtn4(false);
        se.setVisible(true);
    }//GEN-LAST:event_mntmNewMenuItem_2ActionPerformed

    private void mntmNewMenuItem_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntmNewMenuItem_1ActionPerformed
        dispose();
        setVisible(false);
        Selector se = new Selector();
        dbm.setBtn2(true);
        dbm.setBtn4(false);
        dbm.setTextf(false);
        dbm.setTlabel(false);
        se.setVisible(true);
    }//GEN-LAST:event_mntmNewMenuItem_1ActionPerformed

    /**
     * <p>
     * main.</p>
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstPg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstPg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstPg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstPg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FirstPg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGame;
    private javax.swing.JButton btnNewButton;
    private javax.swing.JPanel contentPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenu mnNewMenu;
    private javax.swing.JMenuItem mntmNewMenuItem_1;
    private javax.swing.JMenuItem mntmNewMenuItem_2;
    private javax.swing.JMenuItem mntmNewMenuItem_3;
    // End of variables declaration//GEN-END:variables
}
